// SPDX-License-Identifier: BUSL-1.1
// Read-only YAML views of what has no editable text form in TIA Portal: hardware, HMI Unified,
// technology objects (from the Openness object model) and tag tables (from the mirrored XML).
import { readdir, readFile, rm } from "node:fs/promises";
import { join, relative, sep } from "node:path";
import { escapeSegment, toYaml, writeFileAtomic } from "@rung/core";
import type { BridgeClient, DescribeNode } from "@rung/bridge-client";

export const VIEW_HEADER = "Generated by rung views — read-only. Change these objects in TIA Portal; rerun `rung views` to refresh.";

type ViewNode = { type: string; name?: string; attributes?: Record<string, string>; [child: string]: unknown };

/** Converts a bridge describe tree into a plain, sorted object suitable for YAML. */
export function toView(n: DescribeNode): ViewNode {
  const out: ViewNode = { type: n.type };
  if (n.name) out.name = n.name;
  const attrs = Object.fromEntries(Object.entries(n.attributes ?? {}).filter(([k]) => k !== "Name").sort(([a], [b]) => (a < b ? -1 : 1)));
  if (Object.keys(attrs).length) out.attributes = attrs;
  for (const [k, list] of Object.entries(n.children ?? {}).sort(([a], [b]) => (a < b ? -1 : 1))) out[k] = list.map(toView);
  return out;
}

export interface ViewsReport {
  written: string[];
  truncated: string[];
}

/** Writes views/<scope>/<object>.yaml (one file per top-level object) and prunes stale files of that scope. */
export async function writeModelViews(root: string, bridge: Pick<BridgeClient, "describe">, scopes: ("hardware" | "hmi" | "techobjects" | "libraries")[] = ["hardware", "hmi", "techobjects", "libraries"]): Promise<ViewsReport> {
  const report: ViewsReport = { written: [], truncated: [] };
  for (const scope of scopes) {
    const tree = await bridge.describe(scope);
    if (tree.truncated) report.truncated.push(scope);
    const dir = join(root, "views", scope);
    const keep = new Set<string>();
    for (const [group, list] of Object.entries(tree.children ?? {})) {
      for (const node of list) {
        const file = join(dir, group === "Devices" || group === "HmiUnified" || group === "Plcs" || group === "ProjectLibrary" || group === "LibraryManagers" ? "" : group, `${escapeSegment(node.name ?? node.type)}.yaml`);
        await writeFileAtomic(file, toYaml(toView(node), VIEW_HEADER));
        keep.add(file);
        report.written.push(relative(root, file).split(sep).join("/"));
      }
    }
    await prune(dir, keep);
  }
  return report;
}

async function prune(dir: string, keep: Set<string>) {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true, recursive: true });
  } catch {
    return;
  }
  for (const e of entries) {
    const p = join(e.parentPath ?? (e as unknown as { path: string }).path, e.name);
    if (e.isFile() && p.endsWith(".yaml") && !keep.has(p)) await rm(p, { force: true });
  }
}

/**
 * Tag-table views from the mirrored SimaticML (works offline, no bridge needed). A table kept as text (.tags.st)
 * is readable as it is and gets none; views of tables that are gone or became text are removed.
 */
export async function writeTagViews(root: string): Promise<string[]> {
  const written: string[] = [];
  const keep = new Set<string>();
  const walk = async (dir: string): Promise<void> => {
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      const p = join(dir, e.name);
      if (e.isDirectory()) await walk(p);
      else if (e.name.endsWith(".tags.xml")) {
        const xml = await readFile(p, "utf8");
        const rel = relative(join(root, "plc"), p).split(sep).join("/");
        const [device] = rel.split("/");
        const table = e.name.slice(0, -".tags.xml".length);
        const out = join(root, "views", "tags", device!, `${table}.yaml`);
        await writeFileAtomic(out, toYaml({ table: decodeURIComponent(table.replace(/%(?=[0-9A-F]{2})/g, "%")), source: `plc/${rel}`, tags: parseTagRows(xml) }, VIEW_HEADER));
        keep.add(out);
        written.push(relative(root, out).split(sep).join("/"));
      }
    }
  };
  await walk(join(root, "plc"));
  await prune(join(root, "views", "tags"), keep);
  return written;
}

const decode = (s: string) => s.replace(/&quot;/g, '"').replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&apos;/g, "'").replace(/&amp;/g, "&");

export function parseTagRows(xml: string): { name: string; dataType: string; address?: string; comment?: string }[] {
  const rows: { name: string; dataType: string; address?: string; comment?: string }[] = [];
  for (const m of xml.matchAll(/<SW\.Tags\.PlcTag\b[\s\S]*?<\/SW\.Tags\.PlcTag>/g)) {
    const body = m[0];
    const name = /<Name>([^<]*)<\/Name>/.exec(body)?.[1];
    if (!name) continue;
    const dataType = /<DataTypeName>([^<]*)<\/DataTypeName>/.exec(body)?.[1] ?? "?";
    const address = /<LogicalAddress>([^<]*)<\/LogicalAddress>/.exec(body)?.[1];
    const comment = /<MultilingualText\b[^>]*CompositionName="Comment"[\s\S]*?<Text>([^<]*)<\/Text>/.exec(body)?.[1];
    rows.push({ name: decode(name), dataType: decode(dataType), ...(address ? { address } : {}), ...(comment ? { comment: decode(comment) } : {}) });
  }
  return rows;
}
