// SPDX-License-Identifier: BUSL-1.1
import {expect,it} from "vitest";
import type {LiveFrame} from "../src/types.js";
import {TraceRecorder,parseTrace} from "../src/trace.js";
const scope={device:"PLC_1",address:"127.0.0.1",transport:"s7commplus" as const,epoch:1};
const frame=(extra:Partial<LiveFrame>={}):LiveFrame=>({at:1000,scope,state:"live",values:{Count:2,Ready:true},errors:{},observedAt:{Count:998,Ready:999},types:{Count:"DInt",Ready:"Bool"},...extra});
const recorder=()=>new TraceRecorder(["Count","Ready"],100,900);
it("records independent scalar timestamps and immutable snapshots",()=>{const r=recorder(),f=frame();expect(r.append(f,0)).toBe(true);f.values.Count=99;const t=r.finish("duration");expect(t.frames[0]?.cells.Count).toEqual({value:2,observedAt:998,type:"DInt"});expect(t.frames[0]?.cells.Ready?.value).toBe(true);expect(t.source).toBe("s7commplus-subscription");expect(t.coherence).toBe("asynchronous-observations");expect(parseTrace(JSON.stringify(t))).toEqual(t);});
it("keeps explicit stale/error/missing/unsupported gaps and reconnect epochs",()=>{const r=recorder();r.append(frame(),0);r.append(frame({state:"stale"}),100);r.append(frame({at:1200,scope:{...scope,epoch:2},errors:{Count:"Denied"},values:{Count:7}}),200);r.append(frame({at:1300,scope:{...scope,epoch:2},values:{Count:Infinity,Ready:{bad:true}}}),300);const t=r.finish("stopped");expect(t.frames[1]?.cells.Count?.value).toBeNull();expect(t.frames[1]?.cells.Count?.error).toMatch(/stale/);expect(t.frames[2]?.scope.epoch).toBe(2);expect(t.frames[2]?.cells.Count?.error).toBe("Denied");expect(t.frames[2]?.cells.Ready?.error).toMatch(/observed/);expect(t.frames[3]?.cells.Count?.error).toMatch(/scalar/);});
it("refuses mixed targets and backward receipt times without fabricating data",()=>{const r=recorder();r.append(frame(),1);expect(()=>r.append(frame({scope:{...scope,address:"192.168.1.1"}}),2)).toThrow(/target/);expect(()=>r.append(frame(),0)).toThrow(/elapsed/);r.append(frame({at:900}),2);expect(r.finish("stopped").frames[1]?.cells.Count?.error).toMatch(/clock/);});
it("bounds frame capacity and rejects corrupted portable records",()=>{const r=recorder();for(let i=0;i<20000;i++)r.append(frame({at:1000+i}),i);expect(r.append(frame(),20000)).toBe(false);const t=r.finish("stopped");expect(t.stopReason).toBe("capacity");expect(t.frames).toHaveLength(20000);for(const corrupt of [{...t,version:2},{...t,signals:["Count","Count"]},{...t,frames:[{...t.frames[0],elapsedMs:-1}]},{...t,unknown:true},{...t,frames:[{...t.frames[0],cells:{Other:{value:1}}}]}])expect(()=>parseTrace(JSON.stringify(corrupt))).toThrow();expect(()=>new TraceRecorder(["X","x"],100,0)).toThrow();expect(()=>new TraceRecorder(["X"],50,0)).toThrow();});
it("refuses obsolete epochs and timestamps outside the supported date range",()=>{const r=recorder();r.append(frame({scope:{...scope,epoch:2}}),0);expect(()=>r.append(frame(),1)).toThrow(/epoch/);expect(()=>parseTrace(JSON.stringify({...r.finish("stopped"),startedAt:1e100}))).toThrow();});
it("does not hide a cleanup error behind capacity",()=>{const r=recorder();for(let i=0;i<20000;i++)r.append(frame({at:1000+i}),i);expect(r.finish("error").stopReason).toBe("error");});
