// SPDX-License-Identifier: BUSL-1.1
import { describe, it, expect } from "vitest";
import { parse } from "smol-toml";
import { toYaml } from "../src/index.js";

describe("toYaml", () => {
  it("emits nested objects and arrays deterministically", () => {
    const y = toYaml({ name: "PLC_1", attributes: { OrderNumber: "6ES7 516-3AN02-0AB0", Firmware: "V3.1", Position: 1 }, items: [{ name: "PN", ip: "192.168.0.1" }, { name: "DI 16x24VDC" }], empty: [], none: {} }, "generated by rung — read-only");
    expect(y).toBe(
      [
        "# generated by rung — read-only",
        "name: PLC_1",
        "attributes:",
        '  OrderNumber: "6ES7 516-3AN02-0AB0"',
        "  Firmware: V3.1",
        "  Position: 1",
        "items:",
        "  - name: PN",
        '    ip: "192.168.0.1"',
        "  - name: DI 16x24VDC",
        "empty: []",
        "none: {}",
        "",
      ].join("\n"),
    );
  });

  it("quotes values that YAML would reinterpret", () => {
    const y = toYaml({ a: "true", b: "", c: "x: y", d: "123", e: "%I0.0", f: "with 'quotes' #1", g: " lead" });
    expect(y).toContain('a: "true"');
    expect(y).toContain('b: ""');
    expect(y).toContain('c: "x: y"');
    expect(y).toContain('d: "123"');
    expect(y).toContain("e: %I0.0".replace("%I0.0", '"%I0.0"'));
    expect(y).toContain('g: " lead"');
    void parse;
  });
});
