// SPDX-License-Identifier: BUSL-1.1
using System;
using System.IO;
using System.Linq;
using System.Text;
using Rung.Bridge.Core.Model;
using Rung.Bridge.Core.Protocol;

namespace Rung.Bridge.Core
{
    public static class TextNormalizer
    {
        static readonly UTF8Encoding Utf8 = new UTF8Encoding(false);

        /// <summary>Strip UTF-8 BOM, CRLF → LF, exactly one trailing LF (same rule as packages/core normalizeText).</summary>
        public static byte[] Normalize(byte[] data)
        {
            var s = Utf8.GetString(data);
            if (s.Length > 0 && s[0] == '﻿') s = s.Substring(1);
            s = s.Replace("\r\n", "\n");
            if (s.Length > 0 && !s.EndsWith("\n", StringComparison.Ordinal)) s += "\n";
            return Utf8.GetBytes(s);
        }

        /// <summary>Openness requires a UTF-8 BOM on external sources with non-ASCII characters.</summary>
        public static byte[] WithBom(byte[] data)
        {
            if (data.Length >= 3 && data[0] == 0xEF && data[1] == 0xBB && data[2] == 0xBF) return data;
            return new byte[] { 0xEF, 0xBB, 0xBF }.Concat(data).ToArray();
        }

        /// <summary>Normalizes a staged file in place and returns its manifest record.</summary>
        public static ExportFile NormalizeFile(string path, string role)
        {
            var bytes = Normalize(File.ReadAllBytes(path));
            File.WriteAllBytes(path, bytes);
            return new ExportFile { Path = path, Role = role, Sha256 = Bundle.Sha256(bytes) };
        }
    }

    public static class ProtectedYaml
    {
        static string Q(string s) => s == null ? "null" : "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n") + "\"";

        /// <summary>Read-only stand-in for a know-how-protected object (body is not exportable without the password).</summary>
        public static string Render(ObjectEntry e) =>
            "# Know-how protected in TIA Portal. rung cannot read or change its body.\n" +
            "address: " + Q(e.Address) + "\n" +
            "kind: " + Q(e.Kind) + "\n" +
            "blockType: " + Q(e.BlockType) + "\n" +
            "number: " + (e.Number.HasValue ? e.Number.Value.ToString() : "null") + "\n" +
            "language: " + Q(e.Language) + "\n" +
            "readOnly: true\n";
    }

    /// <summary>
    /// Imports need an explicit launch flag: --allow-import (workspace configured for two-way sync)
    /// or --allow-fixture-import, which only works for projects generated by tools/fixtures.
    /// </summary>
    public static class FixtureGuard
    {
        public const string MarkerName = ".rung-fixture";
        public const string MarkerContent = "rung-fixture-v1";

        public static void CheckImport(bool allowImport, bool allowFixtureImport, string projectFilePath)
        {
            if (allowImport) return;
            Check(allowFixtureImport, projectFilePath);
        }

        public static void Check(bool allowed, string projectFilePath)
        {
            if (!allowed) throw new RpcException(ErrorCodes.ReadOnly, "Imports are disabled. rung M1 imports only into generated fixture projects (--allow-fixture-import).");
            var dir = Path.GetDirectoryName(projectFilePath) ?? "";
            var marker = Path.Combine(dir, MarkerName);
            if (!File.Exists(marker) || !File.ReadAllText(marker).StartsWith(MarkerContent, StringComparison.Ordinal))
                throw new RpcException(ErrorCodes.ReadOnly, "Refusing to import: " + projectFilePath + " is not a rung fixture project (missing " + MarkerName + ").");
        }
    }
}
