// SPDX-License-Identifier: BUSL-1.1
using System;
using System.IO;
using System.Linq;
using System.Text;
using Rung.Bridge.Core.Model;
using Rung.Bridge.Core.Protocol;

namespace Rung.Bridge.Core
{
    /// <summary>TIA Portal's exception texts start with "Error when calling method 'X' of type 'Y'." before the part a person needs.</summary>
    public static class TiaText
    {
        static readonly System.Text.RegularExpressions.Regex Prefix =
            new System.Text.RegularExpressions.Regex(@"^\s*Error when calling method '[^']*' of type '[^']*'\.\s*", System.Text.RegularExpressions.RegexOptions.CultureInvariant);

        public static string Clean(string message)
        {
            if (string.IsNullOrEmpty(message)) return message;
            var rest = Prefix.Replace(message, "").Trim();
            return rest.Length == 0 ? message.Trim() : rest;
        }
    }

    public static class TextNormalizer
    {
        static readonly UTF8Encoding Utf8 = new UTF8Encoding(false);

        /// <summary>Strip UTF-8 BOM, CRLF → LF, exactly one trailing LF (same rule as packages/core normalizeText).</summary>
        public static byte[] Normalize(byte[] data)
        {
            var s = Utf8.GetString(data);
            if (s.Length > 0 && s[0] == '﻿') s = s.Substring(1);
            s = s.Replace("\r\n", "\n");
            if (s.Length > 0 && !s.EndsWith("\n", StringComparison.Ordinal)) s += "\n";
            return Utf8.GetBytes(s);
        }

        /// <summary>Openness requires a UTF-8 BOM on external sources with non-ASCII characters.</summary>
        public static byte[] WithBom(byte[] data)
        {
            if (data.Length >= 3 && data[0] == 0xEF && data[1] == 0xBB && data[2] == 0xBF) return data;
            return new byte[] { 0xEF, 0xBB, 0xBF }.Concat(data).ToArray();
        }

        /// <summary>
        /// Bytes handed to GenerateBlocksFromSource: BOM + CRLF, like TIA's own GenerateSource output.
        /// Fact (openness-v20.md): with LF endings TIA adds a blank line at both ends of an SCL body on every import.
        /// </summary>
        public static byte[] ForSourceImport(byte[] data)
        {
            var lf = Normalize(data);
            return WithBom(Utf8.GetBytes(Utf8.GetString(lf).Replace("\n", "\r\n")));
        }

        /// <summary>Normalizes a staged file in place and returns its manifest record.</summary>
        public static ExportFile NormalizeFile(string path, string role)
        {
            var bytes = Normalize(File.ReadAllBytes(path));
            File.WriteAllBytes(path, bytes);
            return new ExportFile { Path = path, Role = role, Sha256 = Bundle.Sha256(bytes) };
        }
    }

    public static class ProtectedYaml
    {
        static string Q(string s) => s == null ? "null" : "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n") + "\"";

        /// <summary>Read-only stand-in for a know-how-protected object (body is not exportable without the password).</summary>
        public static string Render(ObjectEntry e, string instanceOf = null) =>
            "# Know-how protected in TIA Portal. rung cannot read or change its body.\n" +
            "address: " + Q(e.Address) + "\n" +
            "kind: " + Q(e.Kind) + "\n" +
            "blockType: " + Q(e.BlockType) + "\n" +
            "number: " + (e.Number.HasValue ? e.Number.Value.ToString() : "null") + "\n" +
            "language: " + Q(e.Language) + "\n" +
            "readOnly: true\n" +
            (e.IsSystem && e.BlockType == "InstanceDB" && !string.IsNullOrEmpty(instanceOf)
                ? "isSystem: true\ninstanceOf: " + Q(instanceOf) + "\n" : "");
    }

    /// <summary>
    /// Imports need an explicit launch flag: --allow-import (workspace configured for two-way sync)
    /// or --allow-fixture-import, which only works for projects generated by tools/fixtures.
    /// </summary>
    public static class FixtureGuard
    {
        public const string MarkerName = ".rung-fixture";
        public const string MarkerContent = "rung-fixture-v1";

        public static void CheckImport(bool allowImport, bool allowFixtureImport, string projectFilePath)
        {
            if (allowImport) return;
            Check(allowFixtureImport, projectFilePath);
        }

        public static void Check(bool allowed, string projectFilePath)
        {
            if (!allowed) throw new RpcException(ErrorCodes.ReadOnly, "Imports are disabled; start the bridge with --allow-import (or --allow-fixture-import for generated fixture projects).");
            if (!IsFixture(projectFilePath))
                throw new RpcException(ErrorCodes.ReadOnly, "Refusing to import: " + projectFilePath + " is not a rung fixture project (missing " + MarkerName + ").");
        }

        /// <summary>A project generated as a rung fixture (the marker next to it).</summary>
        public static bool IsFixture(string projectFilePath)
        {
            var marker = Path.Combine(Path.GetDirectoryName(projectFilePath) ?? "", MarkerName);
            return File.Exists(marker) && File.ReadAllText(marker).StartsWith(MarkerContent, StringComparison.Ordinal);
        }
    }
}
