// SPDX-License-Identifier: BUSL-1.1
import {afterEach,expect,it,vi} from "vitest";
import {mkdtemp,readFile,writeFile} from "node:fs/promises";
import * as files from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {defaultConfig,saveConfig} from "@rung/core";
import {parseTrace} from "@rung/live";
import {main} from "../src/main.js";
import * as broker from "../src/liveServer.js";
import {OwnerClient} from "@rung/sync";
vi.mock("node:fs/promises",async importOriginal=>({...await importOriginal<typeof files>(),open:vi.fn((...args:Parameters<typeof files.open>)=>importOriginal<typeof files>().then(real=>real.open(...args)))}));
afterEach(()=>vi.restoreAllMocks());
async function setup(){const root=await mkdtemp(join(tmpdir(),"rung-trace-")),config=defaultConfig("fixture.ap20","V20","",["P"]);config.live={plc:{P:{transport:"s7commplus",address:"192.168.250.1",certificateSha256:"a".repeat(64)}}};await saveConfig(root,config);let stop!:()=>void;const io={cwd:root,env:{},stdout:vi.fn(),stderr:vi.fn(),stopSignal:new Promise<void>(r=>stop=r)};return{root,io,stop};}
const args=["trace","record","Count","--device","P","--duration","1","--interval","100","--out","capture.json","--json"];
it("records using one read-only lease, saves timestamps and inspects offline",async()=>{const s=await setup(),close=vi.fn(async()=>{}),release=vi.fn(async()=>{}),read=vi.fn();const open=vi.spyOn(broker,"brokerReader").mockResolvedValue({read,close,subscribe:async(_labels,_ms,cb)=>{cb({at:1000,scope:{device:"P",address:"192.168.250.1",transport:"s7commplus",epoch:1},state:"live",values:{Count:4},errors:{},observedAt:{Count:997}});s.stop();return{close:release};}});expect(await main(args,s.io)).toBe(0);const saved=parseTrace(await readFile(join(s.root,"capture.json"),"utf8"));expect(saved.frames[0]?.cells.Count?.value).toBe(4);expect(saved.stopReason).toBe("stopped");expect(release).toHaveBeenCalledOnce();expect(close).toHaveBeenCalledOnce();expect(read).not.toHaveBeenCalled();open.mockClear();expect(await main(["trace","inspect","capture.json","--json"],s.io)).toBe(0);expect(open).not.toHaveBeenCalled();});
it("refuses bad limits and existing output before starting a broker",async()=>{const s=await setup(),open=vi.spyOn(broker,"brokerReader");for(const bad of [args.map(v=>v==="100"?"50":v),args.map(v=>v==="1"?"NaN":v),args.filter((_,i)=>i!==3&&i!==4)])expect(await main(bad,s.io)).toBe(1);await writeFile(join(s.root,"capture.json"),"original");expect(await main(args,s.io)).toBe(1);expect(open).not.toHaveBeenCalled();expect(await readFile(join(s.root,"capture.json"),"utf8")).toBe("original");});
it("cleans up a lease whose opening completes after stop",async()=>{const s=await setup(),close=vi.fn(async()=>{}),release=vi.fn(async()=>{});vi.spyOn(broker,"brokerReader").mockResolvedValue({read:async()=>[],close,subscribe:async()=>{s.stop();await new Promise(r=>setTimeout(r,10));return{close:release};}});expect(await main(args,s.io)).toBe(0);expect(close).toHaveBeenCalledOnce();expect(release).toHaveBeenCalledOnce();expect(parseTrace(await readFile(join(s.root,"capture.json"),"utf8")).frames).toHaveLength(0);});
it("reports failure and saves an explicit partial-error recording",async()=>{const s=await setup(),close=vi.fn(async()=>{});vi.spyOn(broker,"brokerReader").mockResolvedValue({read:async()=>[],close,subscribe:async()=>{throw new Error("connection failed");}});expect(await main(args,s.io)).toBe(1);expect(close).toHaveBeenCalledOnce();expect(parseTrace(await readFile(join(s.root,"capture.json"),"utf8")).stopReason).toBe("error");expect(s.io.stderr).toHaveBeenCalledWith(expect.stringContaining("connection failed"));});
it("reports malformed offline files without opening the PLC",async()=>{const s=await setup(),open=vi.spyOn(broker,"brokerReader");for(const data of ["{",Buffer.from([255]),"{}"]){await writeFile(join(s.root,"bad.json"),data);expect(await main(["trace","inspect","bad.json"],s.io)).toBe(1);}expect(open).not.toHaveBeenCalled();expect(s.io.stderr).toHaveBeenCalledWith(expect.stringContaining("BAD_ARGUMENT"));});
it("preserves cleanup failures as partial errors and closes the reader",async()=>{const s=await setup(),close=vi.fn(async()=>{}),release=vi.fn(async()=>{throw new Error("release failed");});vi.spyOn(broker,"brokerReader").mockResolvedValue({read:async()=>[],close,subscribe:async()=>{s.stop();return{close:release};}});expect(await main(args,s.io)).toBe(1);expect(close).toHaveBeenCalledOnce();expect(parseTrace(await readFile(join(s.root,"capture.json"),"utf8")).stopReason).toBe("error");});
it("duration bounds pending subscription startup and releases a late lease",async()=>{const s=await setup(),close=vi.fn(async()=>{}),release=vi.fn(async()=>{});let opened!:()=>void;const ready=new Promise<void>(r=>opened=r);vi.useFakeTimers();try{vi.spyOn(broker,"brokerReader").mockResolvedValue({read:async()=>[],close,subscribe:async()=>{opened();await new Promise(r=>setTimeout(r,1500));return{close:release};}});const recording=main(args,s.io);await ready;await vi.advanceTimersByTimeAsync(1600);expect(close).toHaveBeenCalledOnce();expect(await recording).toBe(0);expect(release).toHaveBeenCalledOnce();expect(parseTrace(await readFile(join(s.root,"capture.json"),"utf8")).stopReason).toBe("duration");}finally{vi.useRealTimers();}});
it("releases all resources on an output write failure without reporting success",async()=>{const s=await setup(),close=vi.fn(async()=>{}),release=vi.fn(async()=>{}),fileClose=vi.fn(async()=>{});const realOpen=(await vi.importActual<typeof files>("node:fs/promises")).open;vi.spyOn(files,"open").mockImplementation(async(...values)=>values[1]==="wx"?{writeFile:async()=>{throw new Error("disk full");},close:fileClose} as Awaited<ReturnType<typeof files.open>>:realOpen(...values));vi.spyOn(broker,"brokerReader").mockResolvedValue({read:async()=>[],close,subscribe:async()=>{s.stop();return{close:release};}});expect(await main(args,s.io)).toBe(1);expect(fileClose).toHaveBeenCalledOnce();expect(close).toHaveBeenCalledOnce();expect(release).toHaveBeenCalledOnce();expect(s.io.stdout).not.toHaveBeenCalled();expect(s.io.stderr).toHaveBeenCalledWith(expect.stringContaining("disk full"));});
it("saves a partial-error recording and closes IPC when the broker never acknowledges release",async()=>{
 const s=await setup(),close=vi.fn();let opening!:()=>void,events!:(event:string,p:unknown)=>void;const ready=new Promise<void>(r=>opening=r);
 const owner={subscribe:async(cb:typeof events)=>{events=cb;},close,request:async(method:string,p:{id:string})=>{if(method==="release")return new Promise(()=>{});if(method==="lease"){events("values",{id:p.id,frame:{at:1000,scope:{device:"P",address:"192.168.250.1",transport:"s7commplus",epoch:1},state:"live",values:{Count:4},errors:{},observedAt:{Count:997}}});opening();}return {};}};
 vi.spyOn(OwnerClient,"connect").mockResolvedValue(owner as unknown as OwnerClient);vi.useFakeTimers();let settled=false;
 try{const recording=main(args,s.io).then(code=>{settled=true;return code;});await ready;await vi.advanceTimersByTimeAsync(6500);await new Promise(r=>files.readFile(join(s.root,"capture.json")).then(r,()=>r(undefined)));expect(settled).toBe(true);expect(await recording).toBe(1);expect(close).toHaveBeenCalledOnce();const trace=parseTrace(await readFile(join(s.root,"capture.json"),"utf8"));expect(trace.stopReason).toBe("error");expect(trace.frames[0]?.cells.Count?.value).toBe(4);expect(s.io.stderr).toHaveBeenCalledWith(expect.stringMatching(/release.*timed out.*partial recording/i));}
 finally{vi.useRealTimers();}
});
