// SPDX-License-Identifier: BUSL-1.1
// AGENTS.md generator: a project summary between markers, the rest of the file belongs to the user.
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { writeFileAtomic, type ObjectState } from "@rung/core";
import { WorkspaceIndex } from "@rung/lsp";
import { CodeGraph } from "@rung/graph";

export const BEGIN = "<!-- rung:summary:begin (generated by `rung agents`; edits here are replaced) -->";
export const END = "<!-- rung:summary:end -->";

export async function summarize(root: string, projectPath: string): Promise<string> {
  let objects: ObjectState[] = [];
  try {
    objects = Object.values((JSON.parse(await readFile(join(root, ".rung", "state.json"), "utf8")) as { objects: Record<string, ObjectState> }).objects);
  } catch {
    /* not pulled yet */
  }
  const index = new WorkspaceIndex();
  await index.load(root);
  const graph = CodeGraph.fromIndex(index);
  const devices = [...new Set(objects.map((o) => o.path.split("/")[1]!))].sort();
  const byForm = new Map<string, number>();
  for (const o of objects) byForm.set(o.form, (byForm.get(o.form) ?? 0) + 1);
  const folders = new Map<string, number>();
  for (const o of objects) {
    const parts = o.path.split("/");
    if (parts[2] === "blocks" && parts.length > 4) folders.set(parts.slice(0, 4).join("/"), (folders.get(parts.slice(0, 4).join("/")) ?? 0) + 1);
  }
  const readOnly = objects.filter((o) => o.readOnly).map((o) => o.path);
  const blocks = index.allGlobals().filter((g) => g.block);
  const hubs = [...graph.nodes.values()]
    .filter((n) => n.kind !== "STANDARD" && n.kind !== "SYSTEM")
    .map((n) => ({ n, users: graph.incoming(n.name).length }))
    .filter((x) => x.users > 0)
    .sort((a, b) => b.users - a.users)
    .slice(0, 8);
  const prefixes = new Map<string, number>();
  for (const g of blocks) {
    const m = /^([A-Za-z]{1,6}_)/.exec(g.name);
    if (m) prefixes.set(m[1]!, (prefixes.get(m[1]!) ?? 0) + 1);
  }
  const conventions = [...prefixes.entries()].filter(([, n]) => n >= 3).sort((a, b) => b[1] - a[1]).map(([p, n]) => `\`${p}\` (${n} blocks)`);
  const lines = [
    BEGIN,
    "## Project summary",
    "",
    `- TIA Portal project: \`${projectPath}\``,
    `- PLCs: ${devices.length ? devices.map((d) => `\`${d}\``).join(", ") : "(run rung pull)"}`,
    `- Objects: ${objects.length} (${[...byForm.entries()].sort().map(([f, n]) => `${n} ${f}`).join(", ") || "none yet"})`,
  ];
  if (folders.size) lines.push("- Block folders: " + [...folders.entries()].sort().map(([f, n]) => `\`${f.split("/").slice(3).join("/")}\` (${n})`).join(", "));
  if (conventions.length) lines.push("- Naming prefixes in use: " + conventions.join(", "));
  if (hubs.length) lines.push("- Most used objects (change with care): " + hubs.map((h) => `\`${h.n.name}\` (${h.users} users)`).join(", "));
  lines.push(readOnly.length ? `- Read-only here (${readOnly.length}): ${readOnly.slice(0, 20).map((p) => `\`${p}\``).join(", ")}${readOnly.length > 20 ? ", …" : ""}` : "- Read-only here: none");
  lines.push(END);
  return lines.join("\n") + "\n";
}

/** Inserts or replaces the generated summary in AGENTS.md, keeping everything else. */
export async function writeAgentsFile(root: string, projectPath: string, template: string): Promise<string> {
  const path = join(root, "AGENTS.md");
  let current: string;
  try {
    current = await readFile(path, "utf8");
  } catch {
    current = template;
  }
  const summary = await summarize(root, projectPath);
  const a = current.indexOf(BEGIN);
  const b = current.indexOf(END);
  const next = a >= 0 && b > a ? current.slice(0, a) + summary + current.slice(b + END.length + 1) : current.trimEnd() + "\n\n" + summary;
  await writeFileAtomic(path, next);
  return next;
}
