// SPDX-License-Identifier: BUSL-1.1
import { describe, it, expect } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { DescribeNode } from "@rung/bridge-client";
import { writeModelViews, writeTagViews, toView } from "../src/index.js";

const hw: DescribeNode = {
  type: "Project",
  name: "RungFixture",
  attributes: {},
  children: {
    Devices: [
      {
        type: "Device",
        name: "PLC_1",
        attributes: { Name: "PLC_1", TypeIdentifier: "System:Device.S71500" },
        children: {
          DeviceItems: [
            { type: "DeviceItem", name: "PLC_1", attributes: { OrderNumber: "6ES7 516-3AN02-0AB0", FirmwareVersion: "V3.1", PositionNumber: "1" }, children: { NetworkNodes: [{ type: "Node", name: "PROFINET", attributes: { Address: "192.168.0.1" }, children: {} }] } },
          ],
        },
      },
    ],
    Subnets: [{ type: "Subnet", name: "PN/IE_1", attributes: { NetType: "Ethernet" }, children: {} }],
  },
};

describe("views", () => {
  it("writes hardware views per device and subnet, and prunes stale files", async () => {
    const root = mkdtempSync(join(tmpdir(), "rung-views-"));
    mkdirSync(join(root, "views", "hardware"), { recursive: true });
    writeFileSync(join(root, "views", "hardware", "Old_Device.yaml"), "stale");
    const r = await writeModelViews(root, { describe: async () => hw }, ["hardware"]);
    expect(r.written.sort()).toEqual(["views/hardware/PLC_1.yaml", "views/hardware/Subnets/PN%2FIE_1.yaml"]);
    const y = readFileSync(join(root, "views", "hardware", "PLC_1.yaml"), "utf8");
    expect(y).toMatch(/^# Generated by rung views/);
    expect(y).toContain('OrderNumber: "6ES7 516-3AN02-0AB0"');
    expect(y).toContain('Address: "192.168.0.1"');
    expect(existsSync(join(root, "views", "hardware", "Old_Device.yaml"))).toBe(false);
  });

  it("writes the project library: types, their versions and which blocks are instances", async () => {
    const root = mkdtempSync(join(tmpdir(), "rung-views-"));
    const node = (type: string, name: string, attributes: Record<string, string> = {}, children: DescribeNode["children"] = {}): DescribeNode => ({ type, name, attributes, children });
    const lib: DescribeNode = node("Project", "RungFixture", {}, {
      ProjectLibrary: [
        node("ProjectLibrary", "Project library", {}, {
          Types: [
            node("LibraryTypeSystemFolder", "Types", {}, {
              Types: [
                node("CodeBlockLibraryType", "Fx_Valve", { Name: "Fx_Valve" }, {
                  Versions: [node("CodeBlockLibraryTypeVersion", "1.0.1", { VersionNumber: "1.0.1", State: "Committed" }, { Instances: [node("Instance", "plc:PLC_1/blocks/Fx_Valve")] })],
                }),
              ],
            }),
          ],
        }),
      ],
    });
    const r = await writeModelViews(root, { describe: async () => lib }, ["libraries"]);
    expect(r.written).toEqual(["views/libraries/Project library.yaml"]);
    const y = readFileSync(join(root, "views", "libraries", "Project library.yaml"), "utf8");
    expect(y).toContain('name: "1.0.1"');
    expect(y).toContain('name: "plc:PLC_1/blocks/Fx_Valve"');
  });

  it("sorts attributes and children for stable diffs", () => {
    const v = toView({ type: "X", name: "n", attributes: { b: "2", a: "1", Name: "n" }, children: { Z: [], A: [] } });
    expect(Object.keys(v)).toEqual(["type", "name", "attributes", "A", "Z"]);
    expect(Object.keys(v.attributes!)).toEqual(["a", "b"]);
  });

  it("renders tag tables from mirrored XML", async () => {
    const root = mkdtempSync(join(tmpdir(), "rung-views-"));
    mkdirSync(join(root, "plc", "PLC_1", "tags"), { recursive: true });
    writeFileSync(
      join(root, "plc", "PLC_1", "tags", "Fx_Inputs.tags.xml"),
      '<Document><SW.Tags.PlcTagTable><AttributeList><Name>Fx_Inputs</Name></AttributeList><ObjectList><SW.Tags.PlcTag ID="1"><AttributeList><DataTypeName>Bool</DataTypeName><LogicalAddress>%I0.0</LogicalAddress><Name>Start &amp; Go</Name></AttributeList><ObjectList><MultilingualText ID="2" CompositionName="Comment"><ObjectList><MultilingualTextItem><AttributeList><Culture>en-US</Culture><Text>start button</Text></AttributeList></MultilingualTextItem></ObjectList></MultilingualText></ObjectList></SW.Tags.PlcTag></ObjectList></SW.Tags.PlcTagTable></Document>',
    );
    expect(await writeTagViews(root)).toEqual(["views/tags/PLC_1/Fx_Inputs.yaml"]);
    const y = readFileSync(join(root, "views", "tags", "PLC_1", "Fx_Inputs.yaml"), "utf8");
    expect(y).toContain('  - name: "Start & Go"');
    expect(y).toContain('    address: "%I0.0"');
    expect(y).toContain("    comment: start button");
  });
});
